{% set python_min = '3.10' %}
{% set name = "design-by-contract" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/design-by-contract-{{ version }}.tar.gz
  sha256: feacc898d9ab6b7b3ccc8b0eafbfd45b0fa9fe7f002ad16d0778a9a7edf57a27

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - design_by_contract
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/StefanUlbrich/design-by-contract
  doc_url: https://stefanulbrich.github.io/design-by-contract/
  summary: Handy decorator to define contracts with dependency injection in Python 3.10 and above
  license: MIT
  # PR made upstream to bundle in license
  license_file: license.txt

extra:
  recipe-maintainers:
    - StefanUlbrich
    - thewchan
